./script.sh celeg scere 0.3
./script.sh celeg scere 0.4
./script.sh celeg scere 0.5
./script.sh celeg scere 0.6
./script.sh celeg scere 0.7
./script.sh celeg dmela 0.3
./script.sh celeg dmela 0.4
./script.sh celeg dmela 0.5
./script.sh celeg dmela 0.6
./script.sh celeg dmela 0.7
./script.sh celeg hsapi 0.3
./script.sh celeg hsapi 0.4
./script.sh celeg hsapi 0.5
./script.sh celeg hsapi 0.6
./script.sh celeg hsapi 0.7
./script.sh scere dmela 0.3
./script.sh scere dmela 0.4
./script.sh scere dmela 0.5
./script.sh scere dmela 0.6
./script.sh scere dmela 0.7
./script.sh scere hsapi 0.3
./script.sh scere hsapi 0.4
./script.sh scere hsapi 0.5
./script.sh scere hsapi 0.6
./script.sh scere hsapi 0.7
./script.sh dmela hsapi 0.3
./script.sh dmela hsapi 0.4
./script.sh dmela hsapi 0.5
./script.sh dmela hsapi 0.6
./script.sh dmela hsapi 0.7
